### PR TITLE
Fix Hugo website to work on v0.135.0

### LINKED ISSUE #219: Fix Hugo build on v0.135.0
When setting up Hugo and trying to run it locally with `hugo server`, multiple errors where encountered.

The latest sources of Hugo like `getJson` and timestamps don't work anymore.

### PR DESCRIPTION
**Pull request by Gijsreyn**
Fix #219

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/220)

### CODE REVIEW

**Comment by johlju** [comment]
Tested this on v0.135.0 and looking at Maintainers Gael's info is on all maintainers.

**Comment by Gijsreyn** [comment]
@johlju Hey Johan, I saw your post on Discord, but couldn't fully grasp the point. Can you explain what you want me to fix, please?

**Comment by Gijsreyn** [comment]
@johlju Should be fixed! Sorry for the delay.

**Comment by johlju** [comment]
@Gijsreyn thank you for this. I had to update the Azure Pipeline build task to work with v0.135.0, there were a bug in the existing build task that I could not find a way to work around other than just skipping it altogether. But your changes work beautifully. Thank you.

**Comment by johlju** [comment]
It has now been released. Thank you again 🙇‍♂️ 

If you feel up to it and if you have time, maybe you can resolve this one too issue https://github.com/dsccommunity/dsccommunity.org/issues/223? 🙂

**Comment by Gijsreyn** [comment]
No thank you Johan for the review and ofcourse! I'll put it on the list and see if I can solve it. Cheers and have a great weekend ahead. Venom is in the cinema, so I'll be watching that.

**Pull request merged**
