### PR TITLE
Added blog post on renaming master to main

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR adds the blog post on renaming master branch to main.

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159)* status: all files reviewed, 6 unresolved discussions (waiting on @gaelcolas and @PlagueHO)

___
*[content/blog/convert-master-to-main.en.md, line 91 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcBf_l5vYwpJUaqSXx:-MPcBf_l5vYwpJUaqSXy:b-tpo6mn) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L91)):*
> ```
> my should refer to the
> ```

Missing the end of the sentence. 

This row an the previous might also be removed since we mentioned it in the Requirements section. Although having it here can be a reminder if someone skipped that (important) part. :)
___
*[content/blog/convert-master-to-main.en.md, line 94 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcCmOwAJRWWCLgv88Q:-MPcCmOwAJRWWCLgv88R:b7agaoi) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L94)):*
> ```
> the tags uses
> ```

There is no need to fetch and push the tags to the fork? Though, maybe they are not needed in the fork for this particular conversion (they are kept in step 10) :thinking: 
```
git checkout master
git fetch origin master # origin is the remote pointing to upstream DSC Community repository.
git rebase origin/master
git fetch origin --tags # get all (new) tags from origin/master
git push my master --force # my is the remote pointing to fork
git push my --tags # push all (new) tags to my/master
```
___
*[content/blog/convert-master-to-main.en.md, line 137 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcEXiT7QvDFbi9qkbr:-MPcEXiT7QvDFbi9qkbs:besjjqk) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L137)):*
> ```
>  validate these changes work
> ```

This sounded to me like it missed a word...? maybe: "validate that these changes work"
___
*[content/blog/convert-master-to-main.en.md, line 158 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcFG_-0gc8VLoW2cXi:-MPcFG_-0gc8VLoW2cXj:b-c90kpr) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L158)):*
> ```
> branches:
>   master:
> ```

Non-blocking. Curious. So we can't just change `master:` to `main:` and skip the regex? Why is the regex still need to have `^master$`? You probably have dug into this so just curious what you found out.
___
*[content/blog/convert-master-to-main.en.md, line 206 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcJ6XD6wGPUgGELTw0:-MPcJ6XD6wGPUgGELTw1:b59ht3s) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L206)):*
> ```
> For example, this is what the `publish_release` and `send_changelog_PR` tasks
> should look like:
> ```

This sounds like there could be more tasks that need them, is those tasks known? If there are no other tasks that need these maybe we could rephrase to that? :thinking: 
___
*[content/blog/convert-master-to-main.en.md, line 243 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcLPL58rysns_U57pY:-MPcLPL58rysns_U57pZ:bkp5im7) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L243)):*
> ```
> #### Update: source/*.psd1
> ```

Can we escape the `*`: `#### Update: source/\*.psd1`

Make sure it looks okay in Hugo though. Reviewable thinks all text after `*` is bold. :laughing: 
___
*[content/blog/convert-master-to-main.en.md, line 256 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcLsM4DsPjrw-1gXuT:-MPcLsM4DsPjrw-1gXuU:b-4kylj0) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L256)):*
> ```Markdown
> update any references for `master` to `main`.
> 
> #### Commit and push the updated pipeline files
> ```

Before this we could add if the repo is using Codecov.io the file codecov.yml need to be updated as well:

https://github.com/dsccommunity/ActiveDirectoryDsc/blob/05265fbed529eeeb0034d9d76bd1f2ef83b52e92/codecov.yml#L4

**Comment by johlju** [comment]
Awesome work on this! 😃  I have read through it and found only minor things. I'm gonna eat breakfast then I will run through the guide on xFailOverCluster to see if I find anything else. 🙂

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159)* status: all files reviewed, 7 unresolved discussions (waiting on @gaelcolas and @PlagueHO)

___
*[content/blog/convert-master-to-main.en.md, line 291 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPceqc0EWggmVbkpSsO:-MPceqc0EWggmVbkpSsP:b-98m7zy) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/5785eb55623815648b1fa80edbbad1c380b16e0a/content/blog/convert-master-to-main.en.md#L291)):*
> ```
> If you have an Azure DevOps pipeline connected to _your fork_ you should
> run the pipeline to validate that it works correctly.
> ```

If there is, then it automatically executed on push in step 5. Is there a reason to run it again after step 6?

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159)* status: all files reviewed, 8 unresolved discussions (waiting on @gaelcolas and @PlagueHO)

___
*[content/blog/convert-master-to-main.en.md, line 335 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcgsTPB3pZynjhatWz:-MPcgsTPB3pZynjhatX-:b7z2dkv) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/5785eb55623815648b1fa80edbbad1c380b16e0a/content/blog/convert-master-to-main.en.md#L335)):*
> ```
> #### Step 10
> ```

Should have three `###` not four`. Throughout below.

**Review by PlagueHO — COMMENTED** [review]
Should be good to review again! Thanks @johlju  

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-:-MPfXRso3YyVsC_TJoLH:biecvf)* status: 14 of 15 files reviewed, 7 unresolved discussions (waiting on @gaelcolas and @johlju)

___
*[content/blog/convert-master-to-main.en.md, line 91 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcBf_l5vYwpJUaqSXx:-MPfRgs15oCctSQaE-e4:b-4cfmrp) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L91)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> my should refer to the
> ```

Missing the end of the sentence. 

This row an the previous might also be removed since we mentioned it in the Requirements section. Although having it here can be a reminder if someone skipped that (important) part. :)
</blockquote></details>

Fixed! good catch!
___
*[content/blog/convert-master-to-main.en.md, line 94 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcCmOwAJRWWCLgv88Q:-MPfRzRB05lx_oiZz5z_:btsaaof) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L94)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> the tags uses
> ```

There is no need to fetch and push the tags to the fork? Though, maybe they are not needed in the fork for this particular conversion (they are kept in step 10) :thinking: 
```
git checkout master
git fetch origin master # origin is the remote pointing to upstream DSC Community repository.
git rebase origin/master
git fetch origin --tags # get all (new) tags from origin/master
git push my master --force # my is the remote pointing to fork
git push my --tags # push all (new) tags to my/master
```

</blockquote></details>

Great point. I think it shouldn't really matter here, because the tags will still be in the origin and we're not actually modifying any in this process.... but it can't hurt so I added the lines and tweaked comments.
___
*[content/blog/convert-master-to-main.en.md, line 137 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcEXiT7QvDFbi9qkbr:-MPfSURW0a8iLNhjgvQt:bizhrc9) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L137)):*
>  validate these changes work
Both wordings are grammatically correct, but I like yours better so changed :)
___
*[content/blog/convert-master-to-main.en.md, line 158 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcFG_-0gc8VLoW2cXi:-MPfSd5t9v4hO9QYK4yh:bnx9rk6) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L158)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> branches:
>   master:
> ```

Non-blocking. Curious. So we can't just change `master:` to `main:` and skip the regex? Why is the regex still need to have `^master$`? You probably have dug into this so just curious what you found out.
</blockquote></details>

This took me _ages_ to figure out. `master:` is actually a "key word" in 'GitVersion.yml', and doesn't actually refer to the branch name, it just refers to the default branch - as it were. So changing it to `main:` breaks GitVersion.

My original plan was to have a version of GitVersion.yml that worked for both master and main. Unfortunately I couldn't get that to work - this is left over from that. So I've changed it now to simplify.
___
*[content/blog/convert-master-to-main.en.md, line 206 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcJ6XD6wGPUgGELTw0:-MPfTWjlCdLZhm1Z-Qzp:bdphw4q) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L206)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> For example, this is what the `publish_release` and `send_changelog_PR` tasks
> should look like:
> ```

This sounds like there could be more tasks that need them, is those tasks known? If there are no other tasks that need these maybe we could rephrase to that? :thinking: 
</blockquote></details>

It is possible there are other tasks that need these variables, but I haven't come across them... yet. If we do find them, Sampler will also need to be updated to read these variables. I've added a note indicating this and a recommendation to raise the issue in Sampler so that we can make adjustments there.
___
*[content/blog/convert-master-to-main.en.md, line 243 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcLPL58rysns_U57pY:-MPfUsU_6tSs5oMpURPr:boj1qgt) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L243)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #### Update: source/*.psd1
> ```

Can we escape the `*`: `#### Update: source/\*.psd1`

Make sure it looks okay in Hugo though. Reviewable thinks all text after `*` is bold. :laughing: 
</blockquote></details>

Good catch. Done.
___
*[content/blog/convert-master-to-main.en.md, line 256 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcLsM4DsPjrw-1gXuT:-MPfUzwO9YUO_8C9cg_a:bomxau5) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L256)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Before this we could add if the repo is using Codecov.io the file codecov.yml need to be updated as well:

https://github.com/dsccommunity/ActiveDirectoryDsc/blob/05265fbed529eeeb0034d9d76bd1f2ef83b52e92/codecov.yml#L4
</blockquote></details>

Good catch. I hadn't updated to use CodeCov.io at the moment so missed this. Done.
___
*[content/blog/convert-master-to-main.en.md, line 291 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPceqc0EWggmVbkpSsO:-MPfW104A1l4n6AYK5z9:b-jbbbsh) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/5785eb55623815648b1fa80edbbad1c380b16e0a/content/blog/convert-master-to-main.en.md#L291)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> If you have an Azure DevOps pipeline connected to _your fork_ you should
> run the pipeline to validate that it works correctly.
> ```

If there is, then it automatically executed on push in step 5. Is there a reason to run it again after step 6?
</blockquote></details>

Good question. It should execute automatically, so this was mostly about validating that the build was successful. I've tweaked the wording to indicate this.
___
*[content/blog/convert-master-to-main.en.md, line 335 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcgsTPB3pZynjhatWz:-MPfX-A24N6SnSWB8mTt:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/5785eb55623815648b1fa80edbbad1c380b16e0a/content/blog/convert-master-to-main.en.md#L335)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> #### Step 10
> ```

Should have three `###` not four`. Throughout below.
</blockquote></details>

Done.

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159)* status: all files reviewed, 2 unresolved discussions (waiting on @gaelcolas and @PlagueHO)

___
*[content/blog/convert-master-to-main.en.md, line 158 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcFG_-0gc8VLoW2cXi:-MPi5aus3XIiqtaz8i3j:b-r8f306) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L158)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This took me _ages_ to figure out. `master:` is actually a "key word" in 'GitVersion.yml', and doesn't actually refer to the branch name, it just refers to the default branch - as it were. So changing it to `main:` breaks GitVersion.

My original plan was to have a version of GitVersion.yml that worked for both master and main. Unfortunately I couldn't get that to work - this is left over from that. So I've changed it now to simplify.
</blockquote></details>

I read up on this too and it is not very clear that `master:` is a keyword, someone really didn't think that one through, it is not very intuitive. :wink: I bet you had difficulty figuring it out, i spent like 15 minutes and then "ah, it is faster to ask". :smiley: 

It can be a question in the Plaster template in Sampler what the name of the default branch should be.
___
*[content/blog/convert-master-to-main.en.md, line 243 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcLPL58rysns_U57pY:-MPi6qY59oyUizHJvn79:b49qcx9) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L243)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Good catch. Done.
</blockquote></details>

It didn't help for Reviewable. :confused: But it doesn't matter. Bug in Reviewable. :slightly_smiling_face: It looks good now. 
___
*[content/blog/convert-master-to-main.en.md, line 299 at r3](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPi7D_d65V2Mqr8rBkv:-MPi7D_d65V2Mqr8rBkw:b-phweq8) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/6a1cac34a21512bd386d12fceaf449ffac7829f9/content/blog/convert-master-to-main.en.md#L299)):*
> ```
> `.codecov.yml`
> ```

Should be "`.codecov.yml` or  `codecov.yml`". FYI. Codecov.io recommend to rename the file to `codecov.yml` (without the prefied '.') to avoid edge case issues.
___
*[content/blog/convert-master-to-main.en.md, line 393 at r3](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPi7mKC4kFH4ygLudim:-MPi7mKC4kFH4ygLudin:b-ebro2h) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/6a1cac34a21512bd386d12fceaf449ffac7829f9/content/blog/convert-master-to-main.en.md#L393)):*
> ```
> git pull origin master
> ```

At this point I had deleted the local branch 'master' and also in my fork. I was standing in the local branch 'main'.

If we done a squash or a rebase merge the commit SHA is different in the fork branch 'main' (`7a151b6`) and the upstream branch 'master' (`6e3320e`)

Also having done changes on two different machines this local branch 'main' did not have all commits from the fork.

 If `git` has been configured to use rebase on pull (like I have) and you do `git pull` on the local 'main' branch and you used a squash merge this will end up having to resolve conflicts. I think we need to be more explicit what we do here.

I think we should do this, it didn't result in a need to resolve conflicts when I did a rebase merge (I reverted the change in master and sent in a new PR to verify doing rebase).

```
# Must be in this local branch
git checkout main 

# Get and rebase changes from fork
git fetch my/main
git rebase my/main

# Get and rebase changes from upstream
git fetch origin/master
git rebase origin/master

# Overwrite fork with all commits from upstream
git push my main --force

# Push your fork main branch as main branch
git push -u origin main
```

**Comment by johlju** [comment]
@PlagueHO That was the last review comments I had. xFailOverCluster has been switch default branch now. Awesome work! 😄

**Review by PlagueHO — COMMENTED** [review]
Thanks @johlju - glad the process worked!!!! I've made the changes should be ready for review now!

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-:-MPl7h22EC7VBWsimAzo:b-suzaf2)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @gaelcolas and @johlju)

___
*[content/blog/convert-master-to-main.en.md, line 158 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPcFG_-0gc8VLoW2cXi:-MPl6dg-CrbvgyUZ0DwW:bu2kbtj) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/28d698a1faf0bee1a5aab89dd88db4d5e98779fa/content/blog/convert-master-to-main.en.md#L158)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I read up on this too and it is not very clear that `master:` is a keyword, someone really didn't think that one through, it is not very intuitive. :wink: I bet you had difficulty figuring it out, i spent like 15 minutes and then "ah, it is faster to ask". :smiley: 

It can be a question in the Plaster template in Sampler what the name of the default branch should be.
</blockquote></details>

That's a good idea. Have raised an issue is Sampler.
___
*[content/blog/convert-master-to-main.en.md, line 299 at r3](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPi7D_d65V2Mqr8rBkv:-MPl7Azv5KrMW_Eyp77p:bt2vr1b) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/6a1cac34a21512bd386d12fceaf449ffac7829f9/content/blog/convert-master-to-main.en.md#L299)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> `.codecov.yml`
> ```

Should be "`.codecov.yml` or  `codecov.yml`". FYI. Codecov.io recommend to rename the file to `codecov.yml` (without the prefied '.') to avoid edge case issues.
</blockquote></details>

Fixed.
___
*[content/blog/convert-master-to-main.en.md, line 393 at r3](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-MPi7mKC4kFH4ygLudim:-MPl7Xa0DE_C6UtFEYrc:b-ggsr1m) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/6a1cac34a21512bd386d12fceaf449ffac7829f9/content/blog/convert-master-to-main.en.md#L393)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> git pull origin master
> ```

At this point I had deleted the local branch 'master' and also in my fork. I was standing in the local branch 'main'.

If we done a squash or a rebase merge the commit SHA is different in the fork branch 'main' (`7a151b6`) and the upstream branch 'master' (`6e3320e`)

Also having done changes on two different machines this local branch 'main' did not have all commits from the fork.

 If `git` has been configured to use rebase on pull (like I have) and you do `git pull` on the local 'main' branch and you used a squash merge this will end up having to resolve conflicts. I think we need to be more explicit what we do here.

I think we should do this, it didn't result in a need to resolve conflicts when I did a rebase merge (I reverted the change in master and sent in a new PR to verify doing rebase).

```
# Must be in this local branch
git checkout main 

# Get and rebase changes from fork
git fetch my/main
git rebase my/main

# Get and rebase changes from upstream
git fetch origin/master
git rebase origin/master

# Overwrite fork with all commits from upstream
git push my main --force

# Push your fork main branch as main branch
git push -u origin main
```

</blockquote></details>

Makes sense - corrected to use your code.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/159#-:-MPmURkd44M3s-6x8cy9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gaelcolas)

**Comment by johlju** [comment]
@PlagueHO blog post is merged. If we have more changes we add those to new PR's. 🙂 Awesome work on this!

**Pull request merged**
