### PR TITLE
Added blog post 'Realizing maintenance windows with DSC'

### PR DESCRIPTION
**Pull request by raandree**
@gaelcolas, here it is. Can you correct the typos that you have found, please?

Two more questions in the blog in general:

1. How do you want to deal with the author information? I have added a small section (which does not render well)

1. The rendering with hugo is fine but the text column is pretty narrow. This is how the page looks like at the 1920x1200 resolution:

image

Is is possible to make the text column adapt dynamically to the browser window?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/50)

### CODE REVIEW

**Comment by PlagueHO** [comment]
I'll give this a review tomorrow if you like. Just short a bit of time today.

**Comment by gaelcolas** [comment]
I'll review that next week (Tue/Wed).
Already read through and it makes sense to me.
Will look Into the author bit, but I think we'll add this from some data and automatically add based on the author property (we'll add to template).
The display/content width is a different matter. We accept PRs ;)

**Comment by raandree** [comment]
Got the message, thanks guys :)

**Comment by johlju** [comment]
Submitted issue https://github.com/dsccommunity/dsccommunity.org/issues/53 to track the narrow blog pages. Labelled it help wanted.

**Comment by gaelcolas** [comment]
@raandree  do you have more edit coming or do you feel that's ready?

**Comment by raandree** [comment]
I think the post is ready. If the change the design another smaller edit may be required.

**Comment by gaelcolas** [comment]
I don't want the cosmetic change (line length) to be blocking this time, but please understand we'd love if you could fix it one day ;)

**Pull request merged**
