### PR TITLE
Update agenda for Feb 9th

### PR DESCRIPTION
**Pull request by johlju**
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[content/community_calls/2021-11-17 Notes.en.md, line 18 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182#-MrTTM6t6s5qqy9eHfsZ:-MrTTM6t6s5qqy9eHfs_:b974qed) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/ca595ec34a46ec783cac7019729a5005721b09a7/content/community_calls/2021-11-17%20Notes.en.md#L18)):*
> ```Markdown
>   Example: https://github.com/dsccommunity/SqlServerDsc/pull/1733/files
> - Azure Devops has deprecated the build worker Windows Server 2016 ('windows-2016').
>   Repos using tha for unit test or integration tests need to move to 'windows-2019',
> ```

Repos using that for unit test or integration tests need to move to 'windows-2019',



_Code quote:_
```Markdown
Repos using tha for unit test or integration tests need to move to 'windows-2019',
```
___
*[content/community_calls/2021-11-17 Notes.en.md, line 19 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182#-MrTTRzhBtC8Fe2cFxB8:-MrTTRzhBtC8Fe2cFxB9:b-70creq) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/ca595ec34a46ec783cac7019729a5005721b09a7/content/community_calls/2021-11-17%20Notes.en.md#L19)):*
> ```Markdown
> - Azure Devops has deprecated the build worker Windows Server 2016 ('windows-2016').
>   Repos using tha for unit test or integration tests need to move to 'windows-2019',
>   'windows-2022', or 'windows-latest' before March 2022.
> ```

We could also mention that this may cause problems with assuring support on older Windows Server 2016 OS's - or even result in support for older OS's to be dropped? Or more discussion required?

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[content/community_calls/2021-11-17 Notes.en.md, line 18 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182#-MrTTM6t6s5qqy9eHfsZ:-MrWxJAU8616XlSZLOOj:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/ca595ec34a46ec783cac7019729a5005721b09a7/content/community_calls/2021-11-17%20Notes.en.md#L18)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Repos using that for unit test or integration tests need to move to 'windows-2019',
</blockquote></details>

Done.
___
*[content/community_calls/2021-11-17 Notes.en.md, line 19 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182#-MrTTRzhBtC8Fe2cFxB8:-MrWxQOm0E5lfddyAJgh:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/ca595ec34a46ec783cac7019729a5005721b09a7/content/community_calls/2021-11-17%20Notes.en.md#L19)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

We could also mention that this may cause problems with assuring support on older Windows Server 2016 OS's - or even result in support for older OS's to be dropped? Or more discussion required?
</blockquote></details>

Done.

**Review by gaelcolas — APPROVED** [review]
Looks good.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/182#-:-MrYRXdl-iks_s1GRVWt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
