### PR TITLE
Added installing GitVersion using release package

### PR DESCRIPTION
**Pull request by johlju**
Since I put time figuring out this I though we add it to the site instead winding up as a private gist. 🙂

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161)

### CODE REVIEW

**Review by PlagueHO — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161)* status: all files reviewed, 6 unresolved discussions (waiting on @johlju)

___
*[content/guidelines/getting-started.md, line 198 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqCPQs7VKkaQdB9O4J:-MPqCPQs7VKkaQdB9O4K:b-cgxcy) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L198)):*
> ```Markdown
> #### macOS
> 
> You install [GitVersion](https://gitversion.net/docs/) using the following
> ```

Minor nitpick: End in colon (:).
___
*[content/guidelines/getting-started.md, line 211 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqCT9Z0nLJ_Xzo5Bsa:-MPqCT9Z0nLJ_Xzo5Bsb:b-cgxcy) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L211)):*
> ```Markdown
> ##### Using Homebrew
> 
> You install [GitVersion](https://gitversion.net/docs/) using the following
> ```

Minor nitpick: End in colon (:).
___
*[content/guidelines/getting-started.md, line 217 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqCVPWB1hw5dKKShQ5:-MPqCVPWB1hw5dKKShQ6:b-8fupts) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L217)):*
> ```Markdown
> ```
> 
> >**NOTE:** You need install [Homebrew](https://brew.sh/) first if you do
> ```

first if -> first, if 
___
*[content/guidelines/getting-started.md, line 222 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqCYvf9ZinCTOFUmLv:-MPqCYvf9ZinCTOFUmLw:b5avvro) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L222)):*
> ```Markdown
> ##### Using release package
> 
> If you don't have or don't want to use Homebrew it is possible to install
> ```

Homebrew it -> Homebrew, it
___
*[content/guidelines/getting-started.md, line 241 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqCl2V8KOf4xiDAaVH:-MPqCl2V8KOf4xiDAaVI:b2kfvdu) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L241)):*
> ```Markdown
> cd ~/gitversion
> 
> wget https://github.com/GitTools/GitVersion/releases/download/5.6.0/gitversion-ubuntu.20.04-x64-5.6.0.tar.gz
> ```

FYI: is it worth defining the version number and ubuntu in a variable and using it through out the script?
___
*[content/guidelines/getting-started.md, line 259 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqD-SF1ekhOLdPzCBY:-MPqD-SF1ekhOLdPzCBZ:b-smh4bw) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L259)):*
> ```Markdown
> ```
> 
> If it returns `Cannot find the .git directory` then it executes correctly.
> ```

then it executes correctly -> then is has executed correctly.
___
*[content/guidelines/getting-started.md, line 260 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqD46fDMgX4_Q3ESP5:-MPqD46fDMgX4_Q3ESP6:byyugcd) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L260)):*
> ```Markdown
> 
> If it returns `Cannot find the .git directory` then it executes correctly.
> First time it executes it can take a while.
> ```

First time -> The first time

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @PlagueHO)

___
*[content/guidelines/getting-started.md, line 217 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqCVPWB1hw5dKKShQ5:-MPrXhmuAq6TBfldR5yj:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L217)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

first if -> first, if 
</blockquote></details>

Done.
___
*[content/guidelines/getting-started.md, line 222 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqCYvf9ZinCTOFUmLv:-MPrXiYC5fmFHn5dr3A7:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L222)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Homebrew it -> Homebrew, it
</blockquote></details>

Done.
___
*[content/guidelines/getting-started.md, line 241 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqCl2V8KOf4xiDAaVH:-MPrXjry9xsBMVDM7XFL:b-qbnyri) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L241)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

FYI: is it worth defining the version number and ubuntu in a variable and using it through out the script?
</blockquote></details>

Done. Also added `#!/bin/bash` so it is more clear to run it in bash. Not tried to install when using PowerShell as the command line.
___
*[content/guidelines/getting-started.md, line 259 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqD-SF1ekhOLdPzCBY:-MPrYBXE2PKL6Q5Ms6tK:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L259)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

then it executes correctly -> then is has executed correctly.
</blockquote></details>

Done.
___
*[content/guidelines/getting-started.md, line 260 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqD46fDMgX4_Q3ESP5:-MPrYBqo7RcuwH0rnl8S:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L260)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

First time -> The first time
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
Sorry @johlju - just one minor tweak. My fault.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-:-MPuSprQByCxkCufQwpd:bdjfn1w)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

___
*[content/guidelines/getting-started.md, line 259 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqD-SF1ekhOLdPzCBY:-MPuSiIo4Hc48ep1Yqd_:bvxp8zz) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L259)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

My bad - should be "then it has executed correctly"

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @PlagueHO)

___
*[content/guidelines/getting-started.md, line 259 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-MPqD-SF1ekhOLdPzCBY:-MPu_XC-D3Cu0o4RQTgD:b-l4egys) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/685d03da165bab296e5272536aa36c6c051caf47/content/guidelines/getting-started.md#L259)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

My bad - should be "then it has executed correctly"
</blockquote></details>

Done. Totally missed that too. I just copy/pasted. :slightly_smiling_face:

**Review by PlagueHO — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/161#-:-MPu_vhk4iEpYMOET56K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
